# Generated by Django 3.2.7 on 2021-09-24 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desg', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('add_line_1', models.CharField(max_length=50)),
                ('add_line_2', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin_code', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateTimeField()),
                ('join', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
