# Generated by Django 3.2.7 on 2021-10-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notification_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='req_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
