# Generated by Django 3.2.7 on 2021-10-03 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notification_req_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='req_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.request'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile'),
        ),
    ]
