# Generated by Django 4.0.3 on 2022-04-20 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_attendance_image_remove_attendance_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.CharField(default='CA401', max_length=10),
        ),
    ]
